export const ACCOUNT_STATUS = {
  UNVERIFIED_EMAIL: 'UNVERIFIED_EMAIL',
  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
  IDENTITY_VERIFIED: 'IDENTITY_VERIFIED',
  VERIFIED_PENDING_LAND: 'VERIFIED_PENDING_LAND',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  ACTIVE: 'ACTIVE',
  REJECTED: 'REJECTED',
};

export const STATUS_LABELS = {
  [ACCOUNT_STATUS.UNVERIFIED_EMAIL]: 'Email Not Verified',
  [ACCOUNT_STATUS.PROFILE_INCOMPLETE]: 'Profile Incomplete',
  [ACCOUNT_STATUS.IDENTITY_VERIFIED]: 'Identity Verified',
  [ACCOUNT_STATUS.VERIFIED_PENDING_LAND]: 'Pending Land Proof',
  [ACCOUNT_STATUS.MANUAL_REVIEW]: 'Manual Review',
  [ACCOUNT_STATUS.PENDING_VERIFICATION]: 'Pending Verification',
  [ACCOUNT_STATUS.ACTIVE]: 'Active',
  [ACCOUNT_STATUS.REJECTED]: 'Rejected',
};

export const STATUS_BADGE_CLASSES = {
  [ACCOUNT_STATUS.UNVERIFIED_EMAIL]: 'bg-gray-100 text-gray-800',
  [ACCOUNT_STATUS.PROFILE_INCOMPLETE]: 'bg-amber-100 text-amber-800',
  [ACCOUNT_STATUS.IDENTITY_VERIFIED]: 'bg-blue-100 text-blue-800',
  [ACCOUNT_STATUS.VERIFIED_PENDING_LAND]: 'bg-amber-100 text-amber-800',
  [ACCOUNT_STATUS.MANUAL_REVIEW]: 'bg-yellow-100 text-yellow-800',
  [ACCOUNT_STATUS.PENDING_VERIFICATION]: 'bg-yellow-100 text-yellow-800',
  [ACCOUNT_STATUS.ACTIVE]: 'bg-bc-green-100 text-bc-green-800',
  [ACCOUNT_STATUS.REJECTED]: 'bg-red-100 text-red-800',
};
