/**
 * Account status states for progressive onboarding
 * Blue Carbon Registry - MoES / NCCR
 *
 * Flow: UNVERIFIED_EMAIL → PROFILE_INCOMPLETE → IDENTITY_VERIFIED → VERIFIED_PENDING_LAND
 *       → PENDING_VERIFICATION → ACTIVE
 * Or: MANUAL_REVIEW (Aadhaar mismatch) → Panchayat verifies
 */
export const ACCOUNT_STATUS = {
  UNVERIFIED_EMAIL: 'UNVERIFIED_EMAIL',
  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
  IDENTITY_VERIFIED: 'IDENTITY_VERIFIED',
  VERIFIED_PENDING_LAND: 'VERIFIED_PENDING_LAND',
  MANUAL_REVIEW: 'MANUAL_REVIEW',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  ACTIVE: 'ACTIVE',
  REJECTED: 'REJECTED',
};

export const STATUS_LABELS = {
  [ACCOUNT_STATUS.UNVERIFIED_EMAIL]: 'Email Not Verified',
  [ACCOUNT_STATUS.PROFILE_INCOMPLETE]: 'Profile Incomplete',
  [ACCOUNT_STATUS.IDENTITY_VERIFIED]: 'Identity Verified',
  [ACCOUNT_STATUS.VERIFIED_PENDING_LAND]: 'Pending Land Proof',
  [ACCOUNT_STATUS.MANUAL_REVIEW]: 'Manual Review',
  [ACCOUNT_STATUS.PENDING_VERIFICATION]: 'Pending Verification',
  [ACCOUNT_STATUS.ACTIVE]: 'Active',
  [ACCOUNT_STATUS.REJECTED]: 'Rejected',
};
