/**
 * Plantation status lifecycle - Blue Carbon Registry
 * PENDING_PANCHAYAT → PENDING_NCCR → VERIFIED → BLOCKCHAIN_PENDING → BLOCKCHAIN_CONFIRMED → TOKEN_MINTED
 * Rejected entries do not proceed.
 */
export const PLANTATION_STATUS = {
  PENDING_PANCHAYAT: 'PENDING_PANCHAYAT',
  PENDING_NCCR: 'PENDING_NCCR',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  BLOCKCHAIN_PENDING: 'BLOCKCHAIN_PENDING',
  BLOCKCHAIN_CONFIRMED: 'BLOCKCHAIN_CONFIRMED',
  TOKEN_MINTED: 'TOKEN_MINTED',
};

export const PLANTATION_STATUS_LABELS = {
  [PLANTATION_STATUS.PENDING_PANCHAYAT]: 'Pending Panchayat',
  [PLANTATION_STATUS.PENDING_NCCR]: 'Pending NCCR',
  [PLANTATION_STATUS.VERIFIED]: 'Verified',
  [PLANTATION_STATUS.REJECTED]: 'Rejected',
  [PLANTATION_STATUS.BLOCKCHAIN_PENDING]: 'On-chain Pending',
  [PLANTATION_STATUS.BLOCKCHAIN_CONFIRMED]: 'Blockchain Confirmed',
  [PLANTATION_STATUS.TOKEN_MINTED]: 'Token Minted',
};

export const LAND_STATUS = {
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
};
